#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(cat /sys/class/power_supply/BAT0/status)

output=""
[ $capacity -ge 0 -a $capacity -le 5 ] && output="  $capacity"
[ $capacity -gt 5 -a $capacity -le 30 ] && output="  $capacity"
[ $capacity -gt 30 -a $capacity -le 60 ] && output="  $capacity"
[ $capacity -gt 60 -a $capacity -le 80 ] && output="  $capacity"
[ $capacity -gt 80 -a $capacity -le 100 ] && output="  $capacity"

[ $status = "Charging" ] && output="$output"

echo $output
