#!/bin/sh

up="󰤨"
down="󰤮"
output=""

for device in /sys/class/net/*; do
    [ $(basename $device) = "lo" ] && continue

    device_status=$(cat $device/operstate)
    device_name=$(basename $device)

    [ $device_status = "up" ] && icon=$up || icon=$down
    output="$output $device_name $icon"
done

echo $output
