#!/bin/sh
#
# В будущем можно выводить красивое имя через 
# nmcli -t -f GENERAL.CONNECTION device show $device_name

up="󰤨"
down="󰤮"
output=""

for device in /sys/class/net/*; do
    [ $(basename $device) = "lo" ] && continue

    device_status=$(cat $device/operstate)
    device_name=$(basename $device)

    if [ $device_status = "up" ]; then
        icon=$up
        connection=$(nmcli -t -f GENERAL.CONNECTION device show $device_name | awk -F ':' '{ print $2 }')
        output="$output $icon $connection"
    fi
done

echo $output
